export { LayoutCompo } from "./layouts/LayoutCompo";
export { AuthPage } from "./auth/AuthPage";
export { Register } from "./auth/Register";
export { ResetPassword } from "./auth/ResetPassword";
export { UpdatePassword } from "./auth/UpdatePassword";
export { Login } from "./auth/Login";
export { FooterCompo } from "./layouts/FooterCompo";
export { HeaderCompo } from "./layouts/HeaderCompo";
export { Home } from "./layouts/Home";
